<html>
  <head>
    <title><%title%></title>
    <link rel='stylesheet' type='text/css' href='/static/layout.css'>
  </head>
  <body>
    <div id='content' class='inner'>
      <h2 class='unnumbered'>Welcome to nasT, a portable <%type%> webserver built only with UNIX utilities</h2>
      <p>To get started, review the documentation.</p>
      <hr/>
      <h4>This was built by Aidan Coyle and Keith Johnson in about 24 hours. Good luck.</h4>
      <p>feel free to change the formatting</p>
  </body>
</html>
